site_name: C3 Documentation
nav:
  - About C3: 'index.md'
  - Installing:
    - Setup: 'setup.md'
    - Your first project: 'firstproject.md'
  - Documentation:
    - Changes from C: 'changesfromc.md'
    - Comparisons with other languages: 'compare.md'
    - Examples: 'examples.md'
    - Modules: 'modules.md'
    - Types: 'types.md'
    - Arrays: 'arrays.md'
    - Functions: 'functions.md'
    - Statements: 'statements.md'
    - Expressions: 'expressions.md'
    - Errors: 'errorhandling.md'
    - Undefined behaviour: 'undefinedbehaviour.md'
    - Conversions: 'conversion.md'
    - Built-in Macros: 'builtinmacros.md'
    - Precedence: 'precedence.md'
    - Generics: 'generics.md'
    - Macros: 'macros.md'
    - Reflection: 'reflection.md'
    - Pre and post conditions: 'preconditions.md'
    - Library: 'library.md'
    - Crazy ideas: 'ideas.md'
    - Naming rules: 'naming.md'
    - Comments & Docs: 'comments.md'
    - Attributes: 'attributes.md'
    - C Interop: 'cinterop.md'
    - Grammar: 'syntax.md'
    - More code examples: 'sample.md'
  - Build system:    
    - Introduction: 'buildintro.md'
    - Project Structure: 'project.md'
    - Commands: 'buildcommands.md'
  - Development:
    - Contribute: 'contribute.md'  
    - Changes: 'changes.md'
    - Rejected ideas: 'rejectedideas.md'
theme:
    name: readthedocs
    hljs_languages:
            - yaml
            - rust
            - ebnf
            - bnf
dev_addr: 192.168.1.4:8000
